export const SET_ESG_PAGE = 'esg/SET_ESG_PAGE';
export const SET_BOUNDARY_EDITION_PAGE = 'esg/SET_BOUNDARY_EDITION_PAGE';
export const SET_SOURCE_PAGE = 'esg/SET_SOURCE_PAGE';
export const SET_STATEMENT_PAGE = 'esg/SET_STATEMENT_PAGE';
export const SET_AUDIT_PAGE = 'esg/SET_AUDIT_PAGE';